"""Event buffers: what changed, when, and which class it belongs to.

A static read answers "what is the value now". An event answers "it changed, and
here is what it was at the time" -- which is the question a master asks when it
wants a sequence rather than a snapshot, and it is why events are held rather
than computed.

Three properties are the whole of this module, and each exists because of a way
event reporting goes wrong in practice.

**An event is generated by a deadband, not by a difference.** Reporting every
read of a measured value floods the buffer with noise no operator asked for. The
deadband is the operator's statement of what counts as a change.

**A quality change always generates an event, whatever the magnitude.** A point
that goes comm-lost while holding the same number has not changed value and has
changed in the way that matters most. A deadband applied to quality would hide
exactly the transitions someone is watching for.

**A full buffer drops its oldest event and says so.** The alternative -- dropping
the newest -- keeps a master reading history while the present goes unreported,
and silence about either is worse than the loss.

Copyright 2026 DER Security Corp. Licensed under the Apache License, Version 2.0.
"""

from __future__ import annotations

import math
import time
from collections import deque
from collections.abc import Iterable
from dataclasses import dataclass, field
from enum import IntEnum
from functools import reduce
from operator import or_

from py1815.objects import AnalogPoint, AnalogQuality, BinaryPoint, BinaryQuality

#: Events a class buffer holds before the oldest is dropped. A master polling on
#: any sane interval never approaches it; a master that has gone away fills it,
#: which is the case the bound is for.
DEFAULT_CAPACITY = 1000


class EventClass(IntEnum):
    """The class an event is reported in.

    Class 0 is not here: it is the static data, which is a read rather than a
    buffer. An event assigned class 0 is an event that is never reported, so
    assigning one is refused rather than quietly honored.
    """

    CLASS_1 = 1
    CLASS_2 = 2
    CLASS_3 = 3


@dataclass(frozen=True)
class AnalogEvent:
    """One analog input change."""

    index: int
    point: AnalogPoint
    timestamp_ms: int


@dataclass(frozen=True)
class BinaryEvent:
    """One binary input change."""

    index: int
    point: BinaryPoint
    timestamp_ms: int


#: Either kind of event. The buffers hold both, because a class is a reporting
#: priority rather than a data type -- a master asking for class 1 wants
#: everything assigned to class 1.
Event = AnalogEvent | BinaryEvent


def now_ms() -> int:
    """Wall-clock milliseconds, which is what a DNP3 timestamp carries.

    Wall clock rather than monotonic, deliberately: the timestamp is for the
    master's sequence of record, and a monotonic reading means nothing to it. A
    clock that steps backwards produces events out of order, which is a real
    hazard and the operator's to resolve -- not one to be hidden here by
    inventing times that look plausible.
    """
    return int(time.time() * 1000)


@dataclass
class _ClassBuffer:
    """One class's events, oldest first, with the overflow it has suffered."""

    capacity: int
    events: deque[Event] = field(default_factory=deque)
    overflowed: bool = False

    def add(self, event: Event) -> None:
        if len(self.events) >= self.capacity:
            self.events.popleft()
            self.overflowed = True
        self.events.append(event)


class EventBuffers:
    """Per-class event storage, and the deadband rules that fill it.

    Holds the last reported value per point so a deadband can be applied against
    what the master was actually told, rather than against the previous reading.
    Comparing against the previous reading lets a value drift past the deadband
    in steps that individually fall inside it, and the master never hears about
    a change that has already happened.
    """

    def __init__(self, *, capacity: int = DEFAULT_CAPACITY) -> None:
        if capacity < 1:
            # Otherwise the first event drops one from an empty buffer, and the
            # IndexError names a deque rather than the configuration.
            raise ValueError(f"capacity is {capacity}; a buffer holds at least one event")
        self._buffers = {cls: _ClassBuffer(capacity) for cls in EventClass}
        self._last_analog: dict[int, AnalogPoint] = {}
        self._last_binary: dict[int, BinaryPoint] = {}

    def count(self, event_class: EventClass) -> int:
        return len(self._buffers[event_class].events)

    @property
    def total(self) -> int:
        return sum(len(buffer.events) for buffer in self._buffers.values())

    def overflowed(self) -> bool:
        """Whether any class has dropped an event since it was last reported."""
        return any(buffer.overflowed for buffer in self._buffers.values())

    def classes_with_events(self) -> set[EventClass]:
        """Which classes have something to report, for the indication bits."""
        return {cls for cls, buffer in self._buffers.items() if buffer.events}

    def peek(self, event_class: EventClass, limit: int | None = None) -> list[Event]:
        """The oldest events of a class, without removing them.

        Reads do not consume. An event leaves the buffer when the master
        confirms the response carrying it, because a response that never arrives
        must not have taken the only copy with it.
        """
        events: list[Event] = list(self._buffers[event_class].events)
        return events[:limit] if limit is not None else events

    def drop(self, events: Iterable[Event]) -> None:
        """Remove events a master has confirmed."""
        confirmed = set(map(id, events))
        for buffer in self._buffers.values():
            remaining = deque(e for e in buffer.events if id(e) not in confirmed)
            buffer.events = remaining

    def clear_overflow(self) -> None:
        """Forget the overflow, once it has been reported to a master."""
        for buffer in self._buffers.values():
            buffer.overflowed = False

    def record_analog(
        self,
        index: int,
        point: AnalogPoint,
        *,
        event_class: EventClass,
        deadband: float = 0.0,
        timestamp_ms: int | None = None,
    ) -> AnalogEvent | None:
        """Record an analog reading, returning the event it generated, if any."""
        previous = self._last_analog.get(index)
        if previous is not None and not self._analog_changed(previous, point, deadband):
            return None

        event = AnalogEvent(index, point, timestamp_ms if timestamp_ms is not None else now_ms())
        self._last_analog[index] = point
        self._buffers[event_class].add(event)
        return event

    def record_binary(
        self,
        index: int,
        point: BinaryPoint,
        *,
        event_class: EventClass,
        timestamp_ms: int | None = None,
    ) -> BinaryEvent | None:
        """Record a binary reading, returning the event it generated, if any.

        No deadband: a binary point has two values, so any change is the whole
        of its range.
        """
        previous = self._last_binary.get(index)
        if previous is not None and not self._binary_changed(previous, point):
            return None

        event = BinaryEvent(index, point, timestamp_ms if timestamp_ms is not None else now_ms())
        self._last_binary[index] = point
        self._buffers[event_class].add(event)
        return event

    @staticmethod
    def _analog_changed(previous: AnalogPoint, current: AnalogPoint, deadband: float) -> bool:
        if _analog_quality_of(previous.flags) != _analog_quality_of(current.flags):
            # Quality first and unconditionally. A point that goes comm-lost
            # holding the same number has not moved and has changed in the way
            # that matters, and a deadband applied here would hide it.
            return True

        # NaN before the deadband, because every comparison involving it is
        # false -- so a reading that went NaN would look unchanged, the master
        # would never hear about it, and the encoder's REFERENCE_ERR would never
        # reach the wire. The recovery back to a real number would be lost the
        # same way. NaN to NaN is genuinely unchanged.
        was_nan, is_nan = math.isnan(previous.value), math.isnan(current.value)
        if was_nan or is_nan:
            return was_nan != is_nan

        return abs(current.value - previous.value) > deadband

    @staticmethod
    def _binary_changed(previous: BinaryPoint, current: BinaryPoint) -> bool:
        if previous.state != current.state:
            return True
        return _binary_quality_of(previous.flags) != _binary_quality_of(current.flags)


#: The quality bits a change is judged on, one mask per point type, each
#: derived from its own enum so that adding a bit to either cannot leave the
#: masks behind.
#:
#: The two enums agree on their lower five bits and diverge at 0x20, where
#: analog has ``OVER_RANGE`` and binary has ``CHATTER_FILTER``; 0x40 is
#: analog-only. A single mask spelled out from ``AnalogQuality`` covered
#: chatter only because those two 0x20 bits happen to collide -- true today,
#: but by coincidence rather than by construction, and silently untrue the
#: moment either enum gains a bit the other lacks.
_ANALOG_QUALITY_MASK: int = reduce(or_, AnalogQuality, 0)

#: Binary, less the state bit: that bit is the value rather than the quality,
#: and ``_binary_changed`` compares it separately. Including it would make
#: every state change register as a quality change as well, and count twice.
_BINARY_QUALITY_MASK: int = reduce(or_, BinaryQuality, 0) & ~BinaryQuality.STATE


def _analog_quality_of(flags: int) -> int:
    return flags & _ANALOG_QUALITY_MASK


def _binary_quality_of(flags: int) -> int:
    return flags & _BINARY_QUALITY_MASK
